### ISSUE TITLE
Need instruction with examples

### ISSUE THREAD

**Issue by standmit** [dic1911/android_URLSanitizer#12]
It is not clear how rules works. Please, describe it with examples: original URL -> clear URL

**Comment by dic1911** [comment]
While you should probably do your own homework, imma try to explain in easier language for this time.

You might have seen URLs like `https://github.com/dic1911?utm_medium=blahblahblah`

That "utm_medium" is so called GET query, which is a common Google Analytics parameter that's used to track users(such as what or who brought them to the page)

This app is used to remove those GET queries before people really open the link in their browser or other apps (ex. official Twitter client), after the example above be handled with this app, it'd be just `https://github.com/dic1911`
