### ISSUE TITLE
Add Spotify to be cleaned

### ISSUE THREAD

**Issue by guerda** [dic1911/android_URLSanitizer#13]
Spotify adds in every share link the following get parameter ?si with a random string. 
Example (shortened) https://open.spotify.com/track/7DbPNM4ACTWabYQJdWLzWB?si=WBPukRgFTJaTNGdA&utm_source=copy-link

It would be great if this could be a default removal.

**Comment by dic1911** [comment]
Thanks for notifying a new rule, I'm now working on the logic for properly updating saved rules, ~~it might take a few days before you could get the new update though.~~

Edit: I was trippin', the logic for updating rule set was already programmed quite some time ago, an update will be released soon.

**Comment by guerda** [comment]
Thanks! That sounds awesome. I just discovered this app via the fediverse.
Let me know how I can help! I can develop, test, review .

**Comment by dic1911** [comment]
The update is now in release page, closing this issue as I tested it and it works fine :)
