### ISSUE TITLE
Using as default browser does not work

### ISSUE THREAD

**Issue by rafaelsgirao** [dic1911/android_URLSanitizer#16]
Setting URLSanitizer as the system's default browser and opening a link results in URLs being sanitized correctly (as shown in a toast notification), but it doesn't know what to do with the URL afterwards.
A system popup at the bottom of the screen appears, saying "`No apps can perform this action.`".
Using Android 12 + URLSanitizer 2.0.3.23 ( F-Droid)

**Comment by dic1911** [comment]
That's due to how the app chooser is designed, which is OS restriction.
