### ISSUE TITLE
How do the url stanitizer rules work?

### ISSUE THREAD

**Issue by StealthBadger747** [dic1911/android_URLSanitizer#17]
I'm trying to make custom rules for autotrader.com with the goal of stripping down the url for sharing.
Is there a guide on how the rules work?

For example there is `@twitter.com` followed by `spm_id_from,action_type_map` are those query parameters linked to `@twitter.com` or are do you have to do something like `scm@aliexpress.com`?

**Comment by dic1911** [comment]
The `@{DOMAIN}` means the rule only applies to the specified `DOMAIN`

For example if you want to filter `userid` query for autotrader.com, just add `userid@autotrader.com` as a rule

**Comment by StealthBadger747** [comment]
Thanks!
