### ISSUE TITLE
cannot add other get queries

### ISSUE THREAD

**Issue by SynapseScribe** [dic1911/android_URLSanitizer#2]
typing inside the app a new key in the field 'enter get query key', does not do anything at all

**Comment by SynapseScribe** [comment]
After seeing the screenshot from fdroid, i realized that actually the 'add new entry' button is not visible (but rather it looks like a line)

**Comment by dic1911** [comment]
Hmm.... the layout may be broken, can you give more detail about your device such as DPI, screen resolution, display size, etc...?

**Comment by SynapseScribe** [comment]
411 dp (seen from developer settings), Size 	6.67 inches, 108.8 cm2 (~88.1% screen-to-body ratio),
Resolution 	qhd+ 1440 x 3120 pixels, 19.5:9 ratio (~516 ppi density)

**Comment by dic1911** [comment]
@fusionneur have you tried latest version?
I think it's already fixed, please confirm and close the issue if fixed.

**Comment by SynapseScribe** [comment]
The entry was added now.
