### ISSUE TITLE
Remove new Youtube url tracker

### ISSUE THREAD

**Issue by Josh-SMU** [dic1911/android_URLSanitizer#20]
Youtube now appends `si=` tracker requests to shared urls. Currently these are not removed by URLSanitizer.

**Comment by dic1911** [comment]
Actually it's there, I just didn't cut another release since there's no big update, I'll find some time to find more tracking queries to add and release new update in few days.

**Comment by dic1911** [comment]
Update is out now :)
https://github.com/dic1911/android_URLSanitizer/releases/tag/3.0.0
