### ISSUE TITLE
short url redirect sanitization

### ISSUE THREAD

**Issue by SynapseScribe** [dic1911/android_URLSanitizer#4]
urls hidden under short urls are not being sanitized now. it would be great to first evaluate the short link to the long format and then strip away the tracking

**Comment by dic1911** [comment]
This requires much more effort than just simply parsing the URL itself.
I'm not even sure I'll ever be able to make it, this sounds like a nice feature to have, though.

**Comment by dic1911** [comment]
Function added in #01b1504050677a63155709ef495c3172cde85ca0 , closing issue.
