### ISSUE TITLE
open sanitize-able urls by default

### ISSUE THREAD

**Issue by jm355** [dic1911/android_URLSanitizer#5]
For example, a reddit app can be set to open all *reddit.com links. It would be cool if we could set this app to be able to open links with any of the query text patterns by default. 

Currently it's kind of annoying to have this app installed. If it's set as the default browser it gets caught in a loop where it sanitizes a link and then passes that link back into itself, so every time I click a link I have to select it and then select the browser I want to use. If it's not the default, then I have to select it to open the link, and then select the browser I want to open the sanitized link with. It would be cool to add a way to select a default browser for the url sanitizer to open sanitized urls with, so it can be used as the default browser and not get stuck in a loop

Sorry if that's a bit unclear, I typed this on my phone and I had a few similar ish ideas bouncing around of how the problem could be solved

**Comment by dic1911** [comment]
This is just how Android handle links, I'm not gonna set default browsers/apps for each site/platform.
