### ISSUE TITLE
Reuse rules with ClearURLs

### ISSUE THREAD

**Issue by cognition9144** [dic1911/android_URLSanitizer#7]
[ClearUrls](https://gitlab.com/KevinRoebert/ClearUrls) has a very comprehensive set of tracking elements remover rules: https://gitlab.com/anti-tracking/ClearURLs/rules. Since there's no reason to do redundant work and those rules are better than what URLSanitizer has, I propose to use those rules instead.

**Comment by dic1911** [comment]
The rules are in different format, actually I already get some most common used rules from there built-in, you're welcome to open a PR to support JSON from ClearURLs if you want to.
