### ISSUE TITLE
Black query text

### ISSUE THREAD

**Issue by skariko** [dic1911/android_URLSanitizer#8]
Hello,
on my Pixel 3a XL with Android 11 it shows all the query text in black with black background:

![Screenshot_20210706-134243~2](https://user-images.githubusercontent.com/25532821/124594485-2130b900-de60-11eb-84bf-18bf4c42716b.png)

**Comment by dic1911** [comment]
Are you using force dark theme or any kind of system-wide theme (ex. substratum)?

**Comment by dic1911** [comment]
Closing this as inactivity for more than 1 month
