### ISSUE TITLE
Blocked string on the main page

### ISSUE THREAD

**Issue by EasyVector** [dic1911/android_URLSanitizer#9]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the main screen, **texts of "App icon made by Smashicons from Flaticon" could not be seen, because this page is not scrollable**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 1.4.1, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts on the main page, and in this circumstance, it seems to be blocked. 

**Steps to reproduce the behavior:**

1. use the largest font and display in the display setting
2. open this app
3. this error could be seen

**Screenshot**

The blocked part is marked in red. The following screenshot is a comparison between the screenshot with the smallest display size and the one with the largest display size. As you could see, in the latter one the string disappeared.

<img src="https://user-images.githubusercontent.com/25502419/131643719-84c2fbd5-e015-4680-ab06-fa04732c1faa.png" alt="copy" width="250"/> <img src="https://user-images.githubusercontent.com/25502419/131643711-3aaca80c-8a41-4dbb-af4a-922b5b4830fc.png" alt="copy" width="250"/> 

**Environment**

1. Version of URLSanitizer : 1.4.1
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by dic1911** [comment]
Closing this as PR merged.
